adding homepage html and aboutpage html
Lever-age/frontend pull request #48
Opened 2017-04-12 00:50 UTC by TheresaWilkin

2017-04-12 14:11 UTC, lottspot requested changes
This is awesome progress! Super excited to see contributions to the frontend coming along! :)

@crsmyz may have more feedback, but the only change I would request is the removal of the .jpg image from the repository. I have feelings about binary files being checked into git (You'll quickly come to learn that I have a really annoying amount of feelings).

Obviously if we aren't going to check our images into the git repository, we need another solution to share and track them... that's probably worth a discussion all its own well outside of the scope of this PR.

Thanks for putting in the time on this work. It's going to be very helpful to get these items struck off of our TODO list.

2017-04-18 01:46 UTC, crsmyz commented
This looks good. I agree with James, we'll have to figure something out as far as large images are concerned. I think one of the only exceptions might be the Leverage logo and anything might have to get relegated to an outside space.

2017-04-18 17:30 UTC, lottspot commented
I think uploading direct to a CDN is a pretty good solution, at least for now. I'm good with this is @crsmyz is 👍

2017-04-18 17:30 UTC, lottspot approved these changes

2017-04-18 22:26 UTC, medy-io approved these changes

2017-04-18 22:26 UTC, merged