Minimize merge conflicts and redundant data
Lever-age/frontend pull request #52
Opened 2017-04-20 14:17 UTC by lottspot

The `dist/` directory appears to contain only derived files; We don't really need these files checked into source control when we already have everything we need to generate them checked in. Checking them in creates weird difficulties, like giving rise to merge conflicts when multiple people make changes, and one person's changes are merge in before another's.

2017-04-20 15:47 UTC, themightychris requested changes

2017-04-20 15:47 UTC, themightychris commented on .gitignore
> +dist
@lottspot I recommend being more specific with .gitignore entries, as I've seen bare names like this become wildcards throwing wrenches into things. This line for example would exclude a file called "dist" several directories down. Use the entry `/dist/` instead which will only apply to a root directory named "dist"

Similarly I'd use `node_modules/` to ignore any directory name "node_modules"  at any depth. Probably less chance of accidents here than with a generic word like "dist", but being as specific as possible is a good practice to establish in .gitignore before you end up with a dozen bare words and wildcards

2017-04-20 15:52 UTC, lottspot commented on .gitignore
> +dist
You are, of course, technically right... but... grumble grumble, the distinction will probably never be noticed in this project, grumble

2017-04-25 00:30 UTC, medy-io approved these changes

2017-05-03 14:30 UTC, merged