Combing Leverage pages and templates together with routing
Lever-age/frontend pull request #55
Opened 2017-05-02 02:18 UTC by crsmyz

This PR tries to effectively combine all of the leverage pages and templates together with routing, bringing a more cohesive environment together that acts more like a web app.

2017-05-03 14:23 UTC, lottspot requested changes
Firstly, I just want to say that the frontend is coming along really, really nicely! It's exciting to see the frontend app come to life! I'm looking forward to working with you guys to plug in our real data to our pages.

The one thing I noticed (which might have actually been introduced in a previous PR which I overlooked) is that it appears we're maintaining component templates in two places sometimes. This also might be my ignorance talking, but I *think* that we don't need both the inline template in candidatelist.compnoent.ts and the html file candidatelist.html. If I'm understanding that correctly, then we should fix that for candidatedetail as well. I would *prefer* that we pick one method and stick to it across all of our components, but for now I'll settle for just not maintaining the same content in two different places.

2017-05-04 00:50 UTC, crsmyz commented
I agree a lot of clean up is needed with some of these templates, and I'll try and get some into this PR. I think it might be valuable to template the HTML files that are above a certain size ie. 100 lines or more as an example that way its easier to read and digest rather than having them gum up our components. While the simpler html templates could be inline because they don't take away as much from the readability of the component.

2017-05-04 19:37 UTC, lottspot commented
I think this is great for now, thanks for putting in the extra work.

2017-05-04 19:37 UTC, lottspot approved these changes

2017-05-04 23:46 UTC, merged